export const TEAM = [
    {
        id: 'jamison',
        name: 'Jamison Howell',
        role: 'Pixel Art, Level Design & Concept Creator',
        description: [
            "I'm Jamie, and while I had the original concept of Roach, EchoForge has transformed it into the survival arcade game we present today.",
            'I presented the team with many of the concepts they have brought to life, and created the enemy and platforming sprites and animations you see in game.',
            'I spend my free time playing cosy and arcade games in between studying and LARPing.',
        ],
        img: '/assets/team/JamisonHowell.jpeg',
        degree: 'Bachelor of Game Design & Development',
    },
    {
        id: 'alexander',
        name: 'Alexander Ramic',
        role: 'Environmental Asset Artist, Animator, Music & SFX Engineer',
        description: [
            'Hello, my name is Alexander and I am primarily the artist of the environmental assets for Roach. I made the various pieces of pipes, irradiated rocks, and barrels as well as more to give Roach that toxic post apocalypse feel.',
            'I also handled the music and sound effects as well as animating my assets and organizing the team in its early stages alongside my two fellow founding members Jamie and Kira before the team welcomed our much needed additional members Lewis and Erica.',
            'Lifelong gamer, an artist with big ambitions, surrealism is my favourite movement of art. Truly grateful to have an amazing team in EchoForge',
        ],
        img: '/assets/team/AlexanderRamic.jpeg',
        degree: 'Bachelor of Game Design & Development',
    },
    {
        id: 'erica',
        name: 'Erica Neale',
        role: 'Character Art Lead',
        description: '...',
        img: '/assets/team/demo-w.png',
        degree: 'Bachelor of Game Design & Development',
    },
    {
        id: 'lewis',
        name: 'Lewis Schneider',
        role: 'Background & Map Design',
        description: '...',
        img: '/assets/team/demo-m.png',
        degree: 'Bachelor of Game Design & Development',
    },
    {
        id: 'kira',
        name: 'Kira Zakirov',
        role: 'Lead Programmer',
        description: [
            'Lead programmer and technical backbone of EchoForge’s Roach project.',
            'Kira developed all gameplay systems, integrated art and audio assets in Unity, and ensured a stable, optimized build through version control and playtesting.',
            'Beyond game development, Kira is an experienced software engineer specializing in front-end architecture, UI/UX, and scalable web applications.',
            'Her mix of technical precision and creative problem-solving drives both the functionality and feel of the team’s work.',
        ],
        img: '/assets/team/kira.jpg',
        degree: 'Bachelor of Game Design & Development',
    },
];
